/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocumentationIndexImport } from './routes/documentation/index'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const DocumentationTablesIndexLazyImport = createFileRoute(
  '/documentation/tables/'
)()
const DocumentationFormsIndexLazyImport = createFileRoute(
  '/documentation/forms/'
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentationIndexRoute = DocumentationIndexImport.update({
  path: '/documentation/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentationTablesIndexLazyRoute =
  DocumentationTablesIndexLazyImport.update({
    path: '/documentation/tables/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/documentation/tables/index.lazy').then((d) => d.Route)
  )

const DocumentationFormsIndexLazyRoute =
  DocumentationFormsIndexLazyImport.update({
    path: '/documentation/forms/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/documentation/forms/index.lazy').then((d) => d.Route)
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationIndexImport
      parentRoute: typeof rootRoute
    }
    '/documentation/forms/': {
      id: '/documentation/forms/'
      path: '/documentation/forms'
      fullPath: '/documentation/forms'
      preLoaderRoute: typeof DocumentationFormsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/documentation/tables/': {
      id: '/documentation/tables/'
      path: '/documentation/tables'
      fullPath: '/documentation/tables'
      preLoaderRoute: typeof DocumentationTablesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DocumentationIndexRoute,
  DocumentationFormsIndexLazyRoute,
  DocumentationTablesIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/documentation/",
        "/documentation/forms/",
        "/documentation/tables/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/documentation/": {
      "filePath": "documentation/index.tsx"
    },
    "/documentation/forms/": {
      "filePath": "documentation/forms/index.lazy.tsx"
    },
    "/documentation/tables/": {
      "filePath": "documentation/tables/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
