/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocumentationTablesImport } from './routes/documentation/tables'

// Create/Update Routes

const DocumentationTablesRoute = DocumentationTablesImport.update({
  path: '/documentation/tables',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documentation/tables': {
      id: '/documentation/tables'
      path: '/documentation/tables'
      fullPath: '/documentation/tables'
      preLoaderRoute: typeof DocumentationTablesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ DocumentationTablesRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/documentation/tables"
      ]
    },
    "/documentation/tables": {
      "filePath": "documentation/tables.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
