export const config = {
  footer: true,
  manual: true,
  page: 0,
  pageSize: 20,
  pages: 6,
  rows: 102,
  loading: false,
  sortBy: [
    {
      id: 'CreationDate',
      desc: true,
    },
  ],
  defaultPageSize: 20,
  pageSizeOptions: [20, 50, 100],
  sortable: true,
  exportable: false,
  filterable: true,
  orderable: false,
  excludable: false,
  configurable: false,
  activeFilter: null,
}
/*
export const headers = [
  {
    type: 'select',
    id: 'select',
    name: 'Select',
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'WidgetId',
    accessor: 'WidgetId',
    style: {},
    name: 'Widget Id',
  },
  {
    width: 110,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'Name',
    name: 'Name',
    accessor: 'Name',
    style: {},
    type: 'sortable',
  },
  {
    width: 110,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'WidgetType',
    name: 'Widget Type',
    accessor: 'WidgetType',
    type: 'sortable',
    style: {},
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'CreationDate',
    name: 'Creation date',
    style: {},
    type: 'date',
  },
  {
    Header: '',
    id: 'grid-actions',
    name: 'Actions',
    sortable: false,
    resizable: false,
    type: 'actions',
    title: 'Actions',
    items: [
      {
        type: 'separator',
        id: 'separator',
        action: () => console.log('separator'),
      },
      {
        id: 'edit',
        label: 'Edit',
        action: (row: IWidgetData) => console.log(row),
      },
      {
        id: 'delete',
        label: 'Delete',
        action: (row: IWidgetData) => console.log(row),
      },
    ],
  },
]*/

export const headers = [
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'first_name',
    name: 'Name',
  },

  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'email',
    name: 'Email',
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'identification_number',
    name: 'Identification Number',
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'user_name',
    name: 'User name',
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: 'user_type',
    name: 'Type',
  },
]

export const filters = [
  {
    key: 'first_name',
    placeholder: 'Filter by name',
  },
  {
    key: 'email',
    placeholder: 'Filter by email',
  },
  {
    key: 'identification_number',
    placeholder: 'Filter by Identification number',
  },
  {
    key: 'user_type',
    placeholder: 'Filter by type',
  },
]

export const tableConfig = {
  headers,
  config,
  filters,
}
